# Generated by Django 4.1.6 on 2023-02-17 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resulttrack',
            name='db_level',
            field=models.IntegerField(default=0),
        ),
    ]
