# Generated by Django 4.1.6 on 2023-02-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_resulttrack_db_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resulttrack',
            name='db_level',
        ),
        migrations.AddField(
            model_name='backgroundtrack',
            name='db_level',
            field=models.IntegerField(default=0),
        ),
    ]
