# Generated by Django 4.1.6 on 2023-02-28 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_remove_resulttrack_db_level_backgroundtrack_db_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequencyTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('track_file', models.FileField(upload_to='freequency')),
                ('db_level', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='resulttrack',
            name='frequency_track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workspace.frequencytrack'),
        ),
    ]
