# Generated by Django 4.1.6 on 2023-03-01 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0004_frequencytrack_resulttrack_frequency_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencytrack',
            name='track_file',
            field=models.FileField(upload_to='frequency'),
        ),
    ]
