# Generated by Django 4.1.6 on 2023-03-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0005_alter_frequencytrack_track_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_val', models.IntegerField(default=0)),
                ('is_running', models.BooleanField(default=False)),
            ],
        ),
    ]
